openapi: 3.0.3
info:
  title: Fibonacci API
  description: API to generate Fibonacci numbers up to a specified count.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /api/fibonacci/{n}:
    get:
      summary: Get Fibonacci numbers
      description: Returns the first `n` Fibonacci numbers starting from 0.
      parameters:
        - name: n
          in: path
          required: true
          description: Number of Fibonacci numbers to return
          schema:
            type: integer
            minimum: 0
      responses:
        "200":
          description: A list of Fibonacci numbers
          content:
            application/json:
              schema:
                type: object
                properties:
                  numbers:
                    type: array
                    items:
                      type: integer
                    example: [0, 1, 1, 2, 3, 5]
        "400":
          description: Bad request (e.g. missing or invalid parameter)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Parameter 'n' must be an integer"

components:
  schemas:
    FibResponse:
      type: object
      properties:
        numbers:
          type: array
          items:
            type: integer
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
